### ISSUE TITLE
Indexing into Float64 calculation

### ISSUE THREAD

**Issue by adinhobl** [mitmath/18337#20]
In this line in Lecture 2, you calculate `val = A[i,j] + B[i,j]`, which should come out as a Float64. In the next line, you index into `val`, the Float64, which somehow works without erroring.
https://github.com/mitmath/18337/blob/cdd7b2078048d83ff1180f7c8832ff2efb3ad058/lecture2/optimizing.jmd#L157

The function compiles and runs correctly, however, I don't know if this is necessary or just leftover from a previous function. In addition, at least on my machine, the `@btime` is faster if you take the indexing out.

**Comment by wi11dey** [comment]
I think the indexing into `Float64` behavior is so `Number`s can be used like a 0-tensor when necessary, like for linear algebra. https://github.com/JuliaLang/julia/pull/1871

It works bc of https://github.com/JuliaLang/julia/blob/master/base/number.jl#L94, and might be slower because it has to check that the index is 1, though I would hope the compiler takes care of it. Fwiw it's actually a couple ms slower _without_ the indexing on my machine, so probably just `@btime` error. I agree it isn't necessary in this case anyway

**Comment by ChrisRackauckas** [comment]
Yes oops, we probably shouldn't index into the val. It's accidentally relying on the 0-tensor behavior. I think in the video I correct it, but I forgot to fix the notes.

**Comment by adinhobl** [comment]
Thanks @wi11dey for the color. It's nice to see some of the reasoning that went into choices.
